global:
  envs:
    USER_BASE_DN: dc=sampleCiam.com
    ENVIRONMENT_NAME: vanguardpoc
    DOMAIN_NAME: ping-devops.com
  labels:
    facile.pingidentity.cloud/admin-env-id: fb45493a-afb5-4b3b-8db6-11e963778f0a
    facile.pingidentity.cloud/admin-user-id: 56aa77be-9442-40ab-b8c0-5d07c2849190
pingOne:
  envRegion: NA
  administration:
    useMyPing: true
    envId: fb45493a-afb5-4b3b-8db6-11e963778f0a
    adminUserId: 56aa77be-9442-40ab-b8c0-5d07c2849190
    workerApp:
      id: 99116941-f763-4e2e-a954-46ab0b28c977
      secret: d1buEKz-BvBti_Svf2g8Zz.s0f~05gBpV7yLhwEzjTEv8Z6nt_yFSLZ5kyk.0hHs
    pfLogonApp:
      id: f01abd8f-8a69-40ed-9003-166d379c50b4
      secret: g-ez5.qkYu4AA7E.rMUtjFiFqDmBtyVc66XBVNPHEQ8SNnSE.i8NwcTU68DgDHex
    paLogonApp:
      id: 4a43a694-8401-4774-be0d-b515a64834d8
      secret: 7H5I.tA9qd.dIVS5g6YjWatFEaG3g3FNaas~q6JBEwvrfvgqVzlZ3CEDxOK9fgoZ
    pdLogonApp:
      id: 4a43a694-8401-4774-be0d-b515a64834d8
      secret: 7H5I.tA9qd.dIVS5g6YjWatFEaG3g3FNaas~q6JBEwvrfvgqVzlZ3CEDxOK9fgoZ
usePingConfig:
  enabled: true
baseline:
  directory:
    enabled: true
capabilities:
  authenticationAuthority:
    enabled: true
  multiFactorAuthentication:
    enabled: false
  accessManager:
    enabled: false
  dynamicAuthorization:
    enabled: false
  risk:
    enabled: true
  verify:
    enabled: false
useCases:
  ciba:
    enabled: false
  consentManagement:
    enabled: false
  delegatedAdministration:
    enabled: true
  accessControl:
    enabled: false
  scim:
    enabled: false
  socialConnections:
    enabled: false
  userProfiles:
    enabled: true
  verifyDemoEnv:
    enabled: false
ping-devops:
  pingfederate-admin:
    enabled: true
    envs:
      SERVER_PROFILE_URL: https://github.com/hinespj/vanguard.git
      SERVER_PROFILE_PATH: VanguardSP/server-profile/pingfederate
      SERVER_PROFILE_BRANCH: main
    workload:
      type: StatefulSet
  pingfederate-engine:
    enabled: true
    envs:
      SERVER_PROFILE_URL: https://github.com/hinespj/vanguard.git
      SERVER_PROFILE_PATH: VanguardSP/server-profile/pingfederate
      SERVER_PROFILE_BRANCH: main
      TAIL_LOG_FILES: /opt/out/instance/log/audit.log /opt/out/instance/log/server.log
      PF_LOG_LEVEL1: DEBUG
  pingdirectory:
    enabled: true
  pingdatasync:
    enabled: false
  pingaccess-admin:
    enabled: false
  pingaccess-engine:
    enabled: false
    envs:
      TAIL_LOG_FILES: >-
        /opt/out/instance/log/pingaccess_engine_audit.log
        /opt/out/instance/log/pingaccess.log
  pingdatagovernance:
    enabled: false
  pingdatagovernancepap:
    enabled: false
  pingdelegator:
    enabled: true
